### ISSUE TITLE
How to stop a timer cron job based on uwsgi cron time signal

### ISSUE THREAD

**Issue by cw1427** [Bahus/uwsgi_tasks#12]
I tried the spooler task which works well.  And for the timer, cron tasks they also works well.  But I didn't find any API could help to stop/ cancel timer cron taskss at running time.

Is there a way to help do that?

**Comment by Bahus** [comment]
Hi! I'm not sure that it's possible to stop timers/crons correctly, since UWSGI Python API does not support "unregister signal for all workers" feature ([see](https://uwsgi-docs.readthedocs.io/en/latest/API.html)). So, it's better to forward your question to uwsgi creators: unbit/uwsgi/issues.

However I think it's possible to re-register signals at least for lazy timers and crons thus disable execution of attached handlers, e.g.:

```python
@cron_lazy(minute=-2, target='mule')
def print_every_2_minutes_after_call(signal_number):
     print('Cron task:', signal_number)

def enable_cron():
    print_every_2_minutes_after_call()

def disable_cron():
    task = print_every_2_minutes_after_call.uwsgi_task
    import uwsgi
    # the code below WON'T stop the cron, but remove handler so nothing is executed when
    # cron job is triggered
    uwsgi.register_signal(task.signal_id, task.target, None)
```

The code above should work when both `enable_cron` and `disable_cron` are executed **in the same worker**, so the usage is pretty limited.

**Comment by cw1427** [comment]
Thanks for the reply. 
One more question about how to make the uwsgi tasks visible? Like to list all of the current tasks jobs including the spooler task.

**Comment by Bahus** [comment]
Do you mean you wan't to get a list of currently executing/executed tasks? If so, I'm afraid such feature is not implemented neither in uwsgi API nor in this package. You can contribute :) or you may look at celery framework.
